Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
15931,27369,-1.160116,-0.244177,0.744250,-0.192350,1.156356,-1.931383,0.409670,-0.364716,-0.516156,...,-0.021714,0.012447,-0.360625,0.514926,0.064194,1.026317,-0.030845,-0.083609,52.90,0.0
15932,27369,-3.058318,3.099206,-4.932555,1.924138,-1.576032,-2.135383,-0.830098,2.228617,-0.312343,...,-0.111526,-0.485223,-0.003945,0.049422,-0.173962,-0.379260,0.171872,-0.236166,99.99,0.0
15933,27369,-0.661806,0.315385,2.011194,-0.438757,-0.554990,-0.668072,0.424651,0.079141,0.126057,...,0.148063,0.177511,0.134794,0.359931,-0.544428,0.181545,0.068546,0.153438,74.58,0.0
15934,27370,1.525348,-1.231442,0.420095,-1.551218,-1.376006,0.100758,-1.455755,0.134876,-1.319056,...,-0.108619,0.084883,-0.051758,-0.815038,0.331989,-0.015837,0.058942,0.011087,6.00,0.0
15935,27371,1.385680,-0.590076,-0.569197,-0.939441,-0.196015,-0.486685,-0.102496,-0.237930,-0.928028,...,-0.255944,-1.055682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15936 entries, 0 to 15935
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    15936 non-null  int64
 1   V1      15936 non-null  float64
 2   V2      15936 non-null  float64
 3   V3      15936 non-null  float64
 4   V4      15936 non-null  float64
 5   V5      15936 non-null  float64
 6   V6      15936 non-null  float64
 7   V7      15936 non-null  float64
 8   V8      15936 non-null  float64
 9   V9      15936 non-null  float64
 10  V10     15936 non-null  float64
 11  V11     15936 non-null  float64
 12  V12     15936 non-null  float64
 13  V13     15936 non-null  float64
 14  V14     15936 non-null  float64
 15  V15     15936 non-null  float64
 16  V16     15936 non-null  float64
 17  V17     15936 non-null  float64
 18  V18     15936 non-null  float64
 19  V19     15936 non-null  float64
 20  V20     15936 non-null  float64
 21  V21     15936 non-null  float64
 22  V22     15936 non-null  float64
 23  V23     15935 non-null  float64
 24  V24     15935 non-null  float64
 25  V25     15935 non-null  float64
 26  V26     15935 non-null  float64
 27  V27     15935 non-null  float64
 28  V28     15935 non-null  float64
 29  Amount  15935 non-null  float64
 30  Class   15935 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 3.8 MB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    15862
1.0       73
Name: Class, dtype: int64

This Dataset is highly unblanced.

0 --> Normal Transaction

1 --> fraudulent transaction

In [ ]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(15862, 31)
(73, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    15862.000000
mean        66.280151
std        188.898885
min          0.000000
25%          5.522500
50%         15.950000
75%         53.890000
max       7712.430000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count      73.000000
mean       90.307123
std       271.634360
min         0.000000
25%         1.000000
50%         1.000000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,12104.432165,-0.219072,0.25000,0.862854,0.272641,-0.105868,0.124522,-0.112681,-0.016178,0.879120,...,0.028173,-0.064056,-0.161585,-0.035040,0.013076,0.117023,0.037111,0.011206,0.005907,66.280151
1.0,15559.643836,-7.929807,6.19312,-11.997831,6.555050,-5.474984,-2.480356,-8.354317,3.668478,-3.086988,...,0.671905,0.441100,-0.295856,-0.358994,-0.328925,0.216076,0.209323,0.927187,0.061380,90.307123

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 73

In [ ]:
legit_sample = legit.sample(n=73)

Concatenating two DataFrames

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
9337,13538,-4.176648,-0.681814,0.602285,2.056717,3.496291,-1.629388,-3.404692,-4.088100,0.916410,...,2.959941,-1.599995,-1.552759,0.234582,0.004513,0.738110,1.383688,-0.333475,0.76,0.0
11835,20319,1.284475,-0.528597,-0.551952,-1.692217,1.390419,3.487251,-1.223489,0.875786,2.954982,...,-0.208136,-0.272552,-0.070785,0.957666,0.636471,-0.711079,0.068018,0.024173,11.85,0.0
2622,2151,-2.574940,-2.669331,-3.080133,2.043551,-11.416881,7.885721,12.219249,-1.828209,-1.475925,...,-0.115580,0.264090,2.219739,-0.771131,0.145438,-0.240517,1.180441,-0.623651,2909.97,0.0
226,150,-0.399880,1.051966,1.390802,0.093132,-0.007699,-0.717559,0.588095,0.085932,-0.310722,...,-0.224926,-0.573766,0.057041,0.329354,-0.302724,0.083883,0.258834,0.096337,0.89,0.0
2390,1948,1.273374,0.166959,0.194318,0.425325,-0.199366,-0.685780,0.089597,-0.216240,0.042828,...,-0.105370,-0.290985,-0.067330,-0.095828,0.447237,0.421676,-0.040637,0.011854,19.99,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
15566,26961,-23.237920,13.487386,-25.188773,6.261733,-17.345188,-4.534989,-17.100492,15.374630,-3.845567,...,1.769708,-1.691973,-1.045673,0.143386,1.611577,-0.221576,1.481233,0.438125,99.99,1.0
15736,27163,-23.914101,13.765942,-25.733734,6.290918,-17.784824,-4.572498,-17.390764,15.794136,-3.819832,...,1.773399,-1.748426,-1.093104,0.147807,1.663792,-0.221024,1.458076,0.430315,99.99,1.0
15751,27187,-24.590245,14.044567,-26.278701,6.320089,-18.224513,-4.609968,-17.681003,16.213627,-3.794093,...,1.777063,-1.804874,-1.140605,0.152234,1.715997,-0.220471,1.434951,0.422492,99.99,1.0
15781,27219,-25.266355,14.323254,-26.823673,6.349248,-18.664251,-4.647403,-17.971212,16.633103,-3.768351,...,1.780701,-1.861318,-1.188167,0.156667,1.768192,-0.219916,1.411855,0.414656,99.99,1.0
15810,27252,-25.942434,14.601998,-27.368650,6.378395,-19.104033,-4.684806,-18.261393,17.052566,-3.742605,...,1.784316,-1.917759,-1.235787,0.161105,1.820378,-0.219359,1.388786,0.406810,99.99,1.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    73
1.0    73
Name: Class, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,12081.356164,-0.224763,0.086512,1.112307,0.368033,-0.253164,0.175169,-0.032562,-0.173466,1.055407,...,-0.046475,0.02302,-0.164760,-0.067435,-0.119732,0.061094,0.106709,0.054943,-0.02497,100.112192
1.0,15559.643836,-7.929807,6.193120,-11.997831,6.555050,-5.474984,-2.480356,-8.354317,3.668478,-3.086988,...,0.671905,0.44110,-0.295856,-0.358994,-0.328925,0.216076,0.209323,0.927187,0.06138,90.307123

Splitting the data into Features & Targets

In [ ]:
X = new_dataset.drop(columns='Class', axis = 1)
Y = new_dataset['Class']

In [ ]:
print(X)

        Time         V1         V2         V3        V4         V5        V6  \
9337   13538  -4.176648  -0.681814   0.602285  2.056717   3.496291 -1.629388
11835  20319   1.284475  -0.528597  -0.551952 -1.692217   1.390419  3.487251
2622    2151  -2.574940  -2.669331  -3.080133  2.043551 -11.416881  7.885721
226      150  -0.399880   1.051966   1.390802  0.093132  -0.007699 -0.717559
2390    1948   1.273374   0.166959   0.194318  0.425325  -0.199366 -0.685780
...      ...        ...        ...        ...       ...        ...       ...
15566  26961 -23.237920  13.487386 -25.188773  6.261733 -17.345188 -4.534989
15736  27163 -23.914101  13.765942 -25.733734  6.290918 -17.784824 -4.572498
15751  27187 -24.590245  14.044567 -26.278701  6.320089 -18.224513 -4.609968
15781  27219 -25.266355  14.323254 -26.823673  6.349248 -18.664251 -4.647403
15810  27252 -25.942434  14.601998 -27.368650  6.378395 -19.104033 -4.684806

              V7         V8        V9  ...       V20       V21       V22  \
9337   -3.404692  -4.088100  0.916410  ... -2.787017  2.959941 -1.599995
11835  -1.223489   0.875786  2.954982  ... -0.015415 -0.208136 -0.272552
2622   12.219249  -1.828209 -1.475925  ...  0.828357 -0.115580  0.264090
226     0.588095   0.085932 -0.310722  ...  0.018253 -0.224926 -0.573766
2390    0.089597  -0.216240  0.042828  ... -0.007063 -0.105370 -0.290985
...          ...        ...       ...  ...       ...       ...       ...
15566 -17.100492  15.374630 -3.845567  ...  1.630787  1.769708 -1.691973
15736 -17.390764  15.794136 -3.819832  ...  1.640037  1.773399 -1.748426
15751 -17.681003  16.213627 -3.794093  ...  1.649202  1.777063 -1.804874
15781 -17.971212  16.633103 -3.768351  ...  1.658289  1.780701 -1.861318
15810 -18.261393  17.052566 -3.742605  ...  1.667304  1.784316 -1.917759

            V23       V24       V25       V26       V27       V28   Amount
9337  -1.552759  0.234582  0.004513  0.738110  1.383688 -0.333475     0.76
11835 -0.070785  0.957666  0.636471 -0.711079  0.068018  0.024173    11.85
2622   2.219739 -0.771131  0.145438 -0.240517  1.180441 -0.623651  2909.97
226    0.057041  0.329354 -0.302724  0.083883  0.258834  0.096337     0.89
2390  -0.067330 -0.095828  0.447237  0.421676 -0.040637  0.011854    19.99
...         ...       ...       ...       ...       ...       ...      ...
15566 -1.045673  0.143386  1.611577 -0.221576  1.481233  0.438125    99.99
15736 -1.093104  0.147807  1.663792 -0.221024  1.458076  0.430315    99.99
15751 -1.140605  0.152234  1.715997 -0.220471  1.434951  0.422492    99.99
15781 -1.188167  0.156667  1.768192 -0.219916  1.411855  0.414656    99.99
15810 -1.235787  0.161105  1.820378 -0.219359  1.388786  0.406810    99.99

[146 rows x 30 columns]

In [ ]:
print(Y)

9337     0.0
11835    0.0
2622     0.0
226      0.0
2390     0.0
        ...
15566    1.0
15736    1.0
15751    1.0
15781    1.0
15810    1.0
Name: Class, Length: 146, dtype: float64

Split the data into Training data & Testing Data

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(146, 30) (116, 30) (30, 30)

Model Training:  Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation: Accuracy Score

In [ ]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [ ]:
print('Accuracy on Training Data :', training_data_accuracy)

Accuracy on Training Data : 0.9827586206896551

In [ ]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accracy = accuracy_score(X_test_prediction, Y_test)

In [ ]:
print('Accuracy on Test Data :', test_data_accracy)

Accuracy on Test Data : 0.9333333333333333